### ISSUE TITLE
ClassNotFoundException: GsonBuilder

### ISSUE THREAD

**Issue by qsef1256** [qsef1256/Capstone2022#1]
```
2022-05-18 00:58:53.377 7430-7430/com.example.capstone2022 E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.capstone2022, PID: 7430
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/gson/GsonBuilder;
        at com.example.capstone2022.util.GsonUtil.getGsonBuilder(GsonUtil.java:28)
        at com.example.capstone2022.util.GsonUtil.<clinit>(GsonUtil.java:21)
        at com.example.capstone2022.util.GsonUtil.toJson(GsonUtil.java:42)
        at com.example.capstone2022.api.corona.CoronaParser.parseData(CoronaParser.java:26)
        at com.example.capstone2022.HomeFragment.lambda$onCreateView$0(HomeFragment.java:88)
        at com.example.capstone2022.HomeFragment$$ExternalSyntheticLambda1.onResponse(Unknown Source:4)
        at com.android.volley.toolbox.StringRequest.deliverResponse(StringRequest.java:82)
        at com.android.volley.toolbox.StringRequest.deliverResponse(StringRequest.java:29)
        at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:102)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7839)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.gson.GsonBuilder" on path: DexPathList[[zip file "/data/app/~~9eHyI37ghmV3V1mGc8eH9Q==/com.example.capstone2022--_DKAbyJXXn59g23UC69lw==/base.apk"],nativeLibraryDirectories=[/data/app/~~9eHyI37ghmV3V1mGc8eH9Q==/com.example.capstone2022--_DKAbyJXXn59g23UC69lw==/lib/x86_64, /system/lib64, /system_ext/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:218)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.example.capstone2022.util.GsonUtil.getGsonBuilder(GsonUtil.java:28) 
        at com.example.capstone2022.util.GsonUtil.<clinit>(GsonUtil.java:21) 
        at com.example.capstone2022.util.GsonUtil.toJson(GsonUtil.java:42) 
        at com.example.capstone2022.api.corona.CoronaParser.parseData(CoronaParser.java:26) 
        at com.example.capstone2022.HomeFragment.lambda$onCreateView$0(HomeFragment.java:88) 
        at com.example.capstone2022.HomeFragment$$ExternalSyntheticLambda1.onResponse(Unknown Source:4) 
        at com.android.volley.toolbox.StringRequest.deliverResponse(StringRequest.java:82) 
        at com.android.volley.toolbox.StringRequest.deliverResponse(StringRequest.java:29) 
        at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:102) 
        at android.os.Handler.handleCallback(Handler.java:938) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loopOnce(Looper.java:201) 
        at android.os.Looper.loop(Looper.java:288) 
        at android.app.ActivityThread.main(ActivityThread.java:7839) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003) 
```

**Comment by qsef1256** [comment]
fixed #1
